swagger: "2.0"
info:
  description: |
    ## Backend APIs for cat breeds search that allows to add a new cat which has name, id , breed group and weight.
  version: "1.0.0"
  title: "Cat Breeds search"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Thao Ho"
    email: "thaoho.turku@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:6868"
basePath: "/v1"
tags:
- name: "cat"
  description: "Everything about cat"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"

# Global consumes and produces
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /cat:
    get:
      tags:
      - "cat"
      summary: "Returns the list of all cats. Empty array if no cats are found."
      operationId: "getCats"
      parameters:
      - name: "page"
        type: "integer"
        in: "query"
        description: "test pagination"
        required: true
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ListOfCats"
            # type: "array"
            # items:
              # $ref: "#/definitions/Building"
        "404":
          description: "Resources not found"
      x-swagger-router-controller: "Cat"
      security:
      - api_key: []
    
    post:
      tags:
      - "cat"
      summary: "Add a new cat to the list."
      operationId: "addCat"
      parameters:
      - in: "body"
        name: "cat"
        description: "Cat object that needs to be added to the list."
        required: true
        schema:
          example:
            name: "Olga"
            weight:
              imperial: "7 - 15"
              metric: "3 - 5"
            breed: "Siberian"
      responses:
        "200":
          description: "Successful adding a new cat."
        "405":
          description: "Invalid input!"
      x-swagger-router-controller: "Cat"
      security:
      - api_key: []
      
  /cat/{catId}:
    get:
      tags:
      - "cat"
      summary: "Find a cat by its ID"
      description: "IDs must be positive integers."
      operationId: "getCatById"
      parameters:
      - name: "catId"
        in: "path"
        description: "ID of the cat that needs to be fetched."
        required: true
        type: "integer"
        minimum: 1
        format: "int64"
      responses:
        "200":
          description: "Successful operation."
          schema:
            $ref: "#/definitions/Cat"
        "400":
          description: "Invalid ID supplied!"
        "404":
          description: "Cat not found!"
      x-swagger-router-controller: "Cat"
      security:
      - api_key: []
    
    put:
      tags:
      - "cat"
      summary: "Update a cat information in the list with JSON in body."
      operationId: "updateCat"
      parameters:
      - name: "catId"
        in: "path"
        description: "ID of the cat that needs to be updated."
        required: true
        type: "integer"
        minimum: 1
        format: "int64"
      - in: "body"
        name: "catInfo"
        description: "Information of the cat that needs to be updated."
        schema:
          example:
            name: "Olga"
            weight:
              imperial: "7 - 15"
              metric: "3 - 5"
            breed: "Siberian"
      responses:
        "200":
          description: "Successful operation."
          schema:
            $ref: "#/definitions/Cat"
        "400":
          description: "Invalid ID supplied!"
        "404":
          description: "Cat not found!"
      x-swagger-router-controller: "Cat"
      security:
      - api_key: []
      
    delete:
      tags:
      - "cat"
      summary: "Delete a cat by its ID."
      description: "IDs must be positive integers."
      operationId: "deleteCat"
      parameters:
      - name: "catId"
        in: "path"
        description: "ID of the cat that needs to be deleted."
        required: true
        type: "integer"
        minimum: 1
        format: "int64"
      responses:
        "204":
          description: "Successful operation."
        "400":
          description: "Invalid ID supplied!"
        "404":
          description: "Cat not found!"
      x-swagger-router-controller: "Cat"
      security:
      - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
    
definitions:
  # Cat model
  Cat:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        description: "Name of the cat"
      weight:
        type: "object"
        properties:
          imperial:
            type: "string"
            description: ""
          metric:
            type: "string"
            description: ""
      breed:
        type: "string"
        description: "Breed of the cat"

  # List of Cats
  ListOfCats:
    type: "array"
    description: "List of all the cats."
    items:
      $ref: "#/definitions/Cat"
    example:
      - id: 1
        name: "Olga"
        weight:
          imperial: "7 - 15"
          metric: "3 - 5"
        breed: "Siberian"
      - id: 2
        name: "Bosse"
        weight:
          imperial: "4 - 12"
          metric: "2 - 4"
        breed: "Exotic"
      - id: 3
        name: "Mochi"
        weight:
          imperial: "6 - 13"
          metric: "4 - 5"
        breed: "Persian"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"